### ISSUE TITLE
New SpanDurationBreakdown version

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-ui#1285]
The SpanDurationBreakdown has new implementation that provides better and more accurate data regarding on how a span's children behave when it's median or p95. The new data will be given under 2 new properties `p50Entries` and `p95Entries` (see example below).
Note that:
- The old property will still be populated for backwards compatibility.
- Note all the spans that appear in `p50Entries` will also be in `p95Entries`, and vice versa.
- The `spanInfo` under the `pXXEntries` its just like the `spanInfo` under of the insight itself.
- Both `duration` and `occurrence` are averages calculated from the time this span duration was median/p95.

``` yaml
{
  "name": "Span Duration Breakdown",
  ...
  "breakdownEntries": [ ... ] // old property
  ...
  "p50Entries": [
    {
      "spanInfo": {
        "uid": "aaf862cc-e24a-11ef-b4e9-0242ac120004",
        "name": "GetUserFromCache",
        "displayName": "GetUserFromCache",
        "instrumentationLibrary": "Global",
        "spanCodeObjectId": "span:Global$_$GetUserFromCache",
        "methodCodeObjectId": null,
        "kind": "Internal"
      },
      "percentageOfCalls": 100.0,
      "duration": {
        "value": 2.0,
        "unit": "ms",
        "raw": 2000000.0
      },
      "occurrence": 1
    },
    ...
  ],
  "p95Entries": [ ... ] // looks just like p50Entries
}
```
